"""
    Theme Parks Wiki V1 API

    api.themeparks.wiki  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.entities_api import EntitiesApi  # noqa: E501


class TestEntitiesApi(unittest.TestCase):
    """EntitiesApi unit test stubs"""

    def setUp(self):
        self.api = EntitiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_entity(self):
        """Test case for get_entity

        Get entity document  # noqa: E501
        """
        pass

    def test_get_entity_children(self):
        """Test case for get_entity_children

        Get all children for a given entity document  # noqa: E501
        """
        pass

    def test_get_entity_live_data(self):
        """Test case for get_entity_live_data

        Get live data for this entity and any child entities  # noqa: E501
        """
        pass

    def test_get_entity_schedule_upcoming(self):
        """Test case for get_entity_schedule_upcoming

        Get entity schedule  # noqa: E501
        """
        pass

    def test_get_entity_schedule_year_month(self):
        """Test case for get_entity_schedule_year_month

        Get entity schedule for a specific month and year  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
