"""
    Theme Parks Wiki V1 API

    api.themeparks.wiki  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.destination_park_entry import DestinationParkEntry
globals()['DestinationParkEntry'] = DestinationParkEntry
from openapi_client.model.destination_entry import DestinationEntry


class TestDestinationEntry(unittest.TestCase):
    """DestinationEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDestinationEntry(self):
        """Test DestinationEntry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DestinationEntry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
