"""
    Theme Parks Wiki V1 API

    api.themeparks.wiki  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.live_queue_standby import LiveQueueSTANDBY


class TestLiveQueueSTANDBY(unittest.TestCase):
    """LiveQueueSTANDBY unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLiveQueueSTANDBY(self):
        """Test LiveQueueSTANDBY"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LiveQueueSTANDBY()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
