"""
    Theme Parks Wiki V1 API

    api.themeparks.wiki  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.entity_data_location import EntityDataLocation
from openapi_client.model.entity_type import EntityType
from openapi_client.model.tag_data import TagData
globals()['EntityDataLocation'] = EntityDataLocation
globals()['EntityType'] = EntityType
globals()['TagData'] = TagData
from openapi_client.model.entity_data import EntityData


class TestEntityData(unittest.TestCase):
    """EntityData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntityData(self):
        """Test EntityData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EntityData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
