"""
    Theme Parks Wiki V1 API

    api.themeparks.wiki  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.entity_type import EntityType
from openapi_client.model.live_queue import LiveQueue
from openapi_client.model.live_show_time import LiveShowTime
from openapi_client.model.live_status_type import LiveStatusType
globals()['EntityType'] = EntityType
globals()['LiveQueue'] = LiveQueue
globals()['LiveShowTime'] = LiveShowTime
globals()['LiveStatusType'] = LiveStatusType
from openapi_client.model.entity_live_data import EntityLiveData


class TestEntityLiveData(unittest.TestCase):
    """EntityLiveData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntityLiveData(self):
        """Test EntityLiveData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EntityLiveData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
