"""
    Theme Parks Wiki V1 API

    api.themeparks.wiki  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.entity_live_data import EntityLiveData
from openapi_client.model.entity_type import EntityType
globals()['EntityLiveData'] = EntityLiveData
globals()['EntityType'] = EntityType
from openapi_client.model.entity_live_data_response import EntityLiveDataResponse


class TestEntityLiveDataResponse(unittest.TestCase):
    """EntityLiveDataResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntityLiveDataResponse(self):
        """Test EntityLiveDataResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EntityLiveDataResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
