"""
    Theme Parks Wiki V1 API

    api.themeparks.wiki  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.destinations_api import DestinationsApi  # noqa: E501


class TestDestinationsApi(unittest.TestCase):
    """DestinationsApi unit test stubs"""

    def setUp(self):
        self.api = DestinationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_destinations(self):
        """Test case for get_destinations

        Get a list of supported destinations available on the live API  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
