"""
    Theme Parks Wiki V1 API

    api.themeparks.wiki  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.boarding_group_state import BoardingGroupState
globals()['BoardingGroupState'] = BoardingGroupState
from openapi_client.model.live_queue_boardinggroup import LiveQueueBOARDINGGROUP


class TestLiveQueueBOARDINGGROUP(unittest.TestCase):
    """LiveQueueBOARDINGGROUP unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLiveQueueBOARDINGGROUP(self):
        """Test LiveQueueBOARDINGGROUP"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LiveQueueBOARDINGGROUP()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
