"""
    Theme Parks Wiki V1 API

    api.themeparks.wiki  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.entity_child import EntityChild
from openapi_client.model.entity_type import EntityType
globals()['EntityChild'] = EntityChild
globals()['EntityType'] = EntityType
from openapi_client.model.entity_children_response import EntityChildrenResponse


class TestEntityChildrenResponse(unittest.TestCase):
    """EntityChildrenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntityChildrenResponse(self):
        """Test EntityChildrenResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EntityChildrenResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
