"""
    Theme Parks Wiki V1 API

    api.themeparks.wiki  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.destination_entry import DestinationEntry
globals()['DestinationEntry'] = DestinationEntry
from openapi_client.model.destinations_response import DestinationsResponse


class TestDestinationsResponse(unittest.TestCase):
    """DestinationsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDestinationsResponse(self):
        """Test DestinationsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DestinationsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
