"""
    Theme Parks Wiki V1 API

    api.themeparks.wiki  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.entity_type import EntityType
from openapi_client.model.schedule_entry import ScheduleEntry
globals()['EntityType'] = EntityType
globals()['ScheduleEntry'] = ScheduleEntry
from openapi_client.model.entity_schedule_response import EntityScheduleResponse


class TestEntityScheduleResponse(unittest.TestCase):
    """EntityScheduleResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntityScheduleResponse(self):
        """Test EntityScheduleResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EntityScheduleResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
