# generated by datamodel-codegen:
#   filename:  https://api.themeparks.wiki/docs/v1.yaml

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import AwareDatetime, BaseModel, Field


class EntityType(Enum):
    DESTINATION = 'DESTINATION'
    PARK = 'PARK'
    ATTRACTION = 'ATTRACTION'
    RESTAURANT = 'RESTAURANT'
    HOTEL = 'HOTEL'
    SHOW = 'SHOW'


class LiveStatusType(Enum):
    OPERATING = 'OPERATING'
    DOWN = 'DOWN'
    CLOSED = 'CLOSED'
    REFURBISHMENT = 'REFURBISHMENT'


class ReturnTimeState(Enum):
    AVAILABLE = 'AVAILABLE'
    TEMP_FULL = 'TEMP_FULL'
    FINISHED = 'FINISHED'


class BoardingGroupState(Enum):
    AVAILABLE = 'AVAILABLE'
    PAUSED = 'PAUSED'
    CLOSED = 'CLOSED'


class PriceData(BaseModel):
    amount: float
    currency: str
    formatted: str | None = None


class STANDBY(BaseModel):
    waitTime: float | None = None


class SINGLERIDER(BaseModel):
    waitTime: float


class RETURNTIME(BaseModel):
    state: ReturnTimeState
    returnStart: AwareDatetime
    returnEnd: AwareDatetime


class PAIDRETURNTIME(BaseModel):
    state: ReturnTimeState
    returnStart: AwareDatetime
    returnEnd: AwareDatetime
    price: PriceData


class BOARDINGGROUP(BaseModel):
    allocationStatus: BoardingGroupState
    currentGroupStart: float
    currentGroupEnd: float
    nextAllocationTime: AwareDatetime
    estimatedWait: float


class PAIDSTANDBY(BaseModel):
    waitTime: float


class LiveQueue(BaseModel):
    STANDBY_1: Annotated[STANDBY | None, Field(alias='STANDBY')] = None
    SINGLE_RIDER: SINGLERIDER | None = None
    RETURN_TIME: RETURNTIME | None = None
    PAID_RETURN_TIME: PAIDRETURNTIME | None = None
    BOARDING_GROUP: BOARDINGGROUP | None = None
    PAID_STANDBY: PAIDSTANDBY | None = None


class LiveShowTime(BaseModel):
    type: str
    startTime: AwareDatetime | None = None
    endTime: AwareDatetime | None = None


class DiningAvailability(BaseModel):
    partySize: float | None = None
    waitTime: float | None = None


class TagData(BaseModel):
    tag: str
    tagName: str
    id: str | None = None
    value: str | float | dict[str, Any] | None = None


class Location(BaseModel):
    latitude: float | None = None
    longitude: float | None = None


class EntityData(BaseModel):
    id: str
    name: str
    entityType: EntityType
    parentId: str | None = None
    destinationId: str | None = None
    timezone: str
    location: Location | None = None
    tags: list[TagData] | None = None


class EntityChild(BaseModel):
    id: str
    name: str
    entityType: EntityType
    externalId: str | None = None
    parentId: str | None = None
    location: Location | None = None


class EntityChildrenResponse(BaseModel):
    id: str | None = None
    name: str | None = None
    entityType: EntityType | None = None
    timezone: str | None = None
    children: list[EntityChild] | None = None


class EntityLiveData(BaseModel):
    id: str
    name: str
    entityType: EntityType
    status: LiveStatusType | None = None
    lastUpdated: AwareDatetime
    queue: LiveQueue | None = None
    showtimes: list[LiveShowTime] | None = None
    operatingHours: list[LiveShowTime] | None = None
    diningAvailability: list[DiningAvailability] | None = None


class EntityLiveDataResponse(BaseModel):
    id: str | None = None
    name: str | None = None
    entityType: EntityType | None = None
    timezone: str | None = None
    liveData: list[EntityLiveData] | None = None


class Type(Enum):
    ADMISSION = 'ADMISSION'
    PACKAGE = 'PACKAGE'
    ATTRACTION = 'ATTRACTION'


class SchedulePriceObject(BaseModel):
    type: Type | None = None
    id: str | None = None
    name: str | None = None
    price: PriceData | None = None
    available: bool | None = None


class Type1(Enum):
    OPERATING = 'OPERATING'
    TICKETED_EVENT = 'TICKETED_EVENT'
    PRIVATE_EVENT = 'PRIVATE_EVENT'
    EXTRA_HOURS = 'EXTRA_HOURS'
    INFO = 'INFO'


class ScheduleEntry(BaseModel):
    date: str
    openingTime: AwareDatetime
    closingTime: AwareDatetime
    type: Type1
    purchases: list[SchedulePriceObject] | None = None


class EntityScheduleResponse(BaseModel):
    id: str | None = None
    name: str | None = None
    entityType: EntityType | None = None
    timezone: str | None = None
    schedule: list[ScheduleEntry] | None = None
    parks: list[EntityScheduleResponse] | None = None
    """
    Only included for destinations, this will list all parks within the destination
    """


class DestinationParkEntry(BaseModel):
    id: str | None = None
    name: str | None = None


class DestinationEntry(BaseModel):
    id: str | None = None
    name: str | None = None
    slug: str | None = None
    externalId: str | None = None
    """
    External entity ID from the source data provider
    """
    parks: list[DestinationParkEntry] | None = None


class DestinationsResponse(BaseModel):
    destinations: list[DestinationEntry] | None = None


EntityScheduleResponse.model_rebuild()
